name: fakebook_homepage
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^5.7.10
  fluttertoast: ^7.0.3
  cupertino_icons: ^0.1.3
  cached_network_image: ^2.2.0+1
  material_design_icons_flutter: ^4.0.5345
  firebase_core : ^0.5.0
  firebase_auth: ^0.18.0+1  #0.14.0+5
  google_sign_in: ^4.5.3 #4.0.7
  cloud_firestore:  ^0.14.0+2 #^0.12.9+5
  image_picker: ^0.6.7+7 #0.6.1+8
  shared_preferences: ^0.5.10 #0.5.3+4
  firebase_storage: ^4.0.0 #3.0.6
  intl: ^0.16.1 #0.15.7
  firebase_messaging: 7.0.0 #6.0.13
  flutter_local_notifications: 1.4.4+4 #1.4.0
  photo_view: ^0.10.2 #0.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/logos/facebook.png
    - assets/logos/google.jpg


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf